# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

matrix:
  include:
  - env: CABALVER=1.18 GHCVER=7.4.2 BUILD=cabal
    addons: {apt: {packages: [cabal-install-1.18,ghc-7.4.2], sources: [hvr-ghc]}}

  - env: CABALVER=1.18 GHCVER=7.6.3 BUILD=cabal
    addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}

  - env: ARGS= BUILD=stack
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-2" BUILD=stack
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver nightly" BUILD=stack
    addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
  - env: CABALVER=head GHCVER=head BUILD=cabal
  - env: ARGS="--resolver nightly" BUILD=stack

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal/packages

before_install:
- case "$BUILD" in
    stack)
      export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH;
      mkdir -p ~/.local/bin;
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
      stack --version
      ;;
    cabal)
      export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH;
      ghc --version;
      cabal --version
      ;;
  esac

install:
- case "$BUILD" in
    stack)
      stack $ARGS setup --no-terminal;
      stack $ARGS build --only-snapshot --test
      ;;
    cabal)
      travis_retry cabal update;
      cabal install --only-dependencies
      ;;
  esac

script:
- case "$BUILD" in
    stack)
      stack $ARGS --no-terminal test --haddock
      ;;
    cabal)
      cabal install --enable-tests
      ;;
  esac
